name: Cargo Release
permissions:
  "contents": "write"

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'

jobs:
  auto-cargo-release:
    runs-on: "ubuntu-20.04"
    needs: tests
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust
        run: rustup update
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Check if version in Cargo.toml has changed
        id: project
        run: |
          git diff-tree --no-commit-id --name-only -r -G'^version ?= ?"*"' --quiet --exit-code "${{ github.ref }}" Cargo.toml
          echo "VERSION_CHANGED=$?" >> $GITHUB_ENV
      - name: Run cargo-release
        if: project.VERSION_CHANGED == "1"
        run: cargo release --execute
