name: Tests

on: push

jobs:
  run-tests:
    runs-on: "ubuntu-20.04"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust
        run: rustup update
      - name: Run tests
        run: cargo test

  release-if-needed:
    runs-on: "ubuntu-20.04"
    needs: run-tests
    # Only run if tests passed and the branch is main.
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Check if version in Cargo.toml has changed
        id: version_changed
        run: |
          ! git diff-tree -r -G'^version ?= ?"*"' --exit-code HEAD Cargo.toml
      - name: Install Rust
        if: steps.version_changed.status == 'success'
        run: rustup update
      - name: Install cargo-release
        if: steps.version_changed.status == 'success'
        run: cargo install cargo-release
      - name: Run cargo-release
        if: steps.version_changed.status == 'success'
        run: cargo release --execute
